// src/components/redirecting.tsx
'use client';

import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion } from 'framer-motion';

export function Redirecting({ show, target }: { show: boolean; target?: string }) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  if (!mounted) return null;

  return createPortal(
    <AnimatePresence>
      {show && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3, ease: 'easeOut' }}
          className="fixed inset-0 z-[9999] flex flex-col items-center justify-center
                     bg-black/70 backdrop-blur-sm text-white"
        >
          <div className="flex flex-row gap-2">
            <div className="w-4 h-4 rounded-full bg-white animate-bounce"></div>
            <div
              className="w-4 h-4 rounded-full bg-white animate-bounce [animation-delay:-.3s]"
            ></div>
            <div
              className="w-4 h-4 rounded-full bg-white animate-bounce [animation-delay:-.5s]"
            ></div>
          </div>

          <motion.p
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.25, duration: 0.4 }}
            className="mt-8 text-lg font-semibold text-center"
          >
            Redirecting{target ? ` to ${target}` : ''}, please wait...
          </motion.p>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  );
}

// src/components/Redirecting.svelte
<script lang="ts">
  import { fly, fade } from 'svelte/transition';
  import { onMount } from 'svelte';

  interface Props {
    show: boolean;
    target?: string;
  }

  let { show = $bindable(false), target }: Props = $props();
  let mounted = $state(false);

  onMount(() => {
    mounted = true;
  });
</script>

{#if mounted && show}
  <div
    class="fixed inset-0 z-[9999] flex flex-col items-center justify-center bg-black/70 backdrop-blur-sm text-white"
    transition:fade={{ duration: 300 }}
  >
    <div class="flex flex-row gap-2">
      <div class="w-4 h-4 rounded-full bg-white animate-bounce"></div>
      <div class="w-4 h-4 rounded-full bg-white animate-bounce [animation-delay:-0.3s]"></div>
      <div class="w-4 h-4 rounded-full bg-white animate-bounce [animation-delay:-0.5s]"></div>
    </div>

    <p 
      class="mt-8 text-lg font-semibold text-center"
      in:fly={{ y: 8, delay: 250, duration: 400 }}
    >
      Redirecting{target ? ` to ${target}` : ''}, please wait...
    </p>
  </div>
{/if}
